# Generated by Django 3.1.3 on 2021-01-13 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seok', '0007_answer_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='hit',
        ),
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.ManyToManyField(related_name='hit_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
